#ifndef __SD1306_OBF_H
#define __SD1306_OBF_H

// IN THE CONTEXT OF SSC342 THIS IS DUPLICATE.
// THIS HEADER IS GIVEN TO STUDENTS IN THEIR SOURCE

// THIS DOESN'T DO ANYTHING, BUT IS KEPT HERE FOR POSTERITY.

// IF YOU HAVE A LINKER ISSUE RELATED TO THIS DISPLAY
// CHECK SOURCE/SSD1306.h

// THE REASON FOR THIS IS BECAUSE SOME THIS HEADER IS PART OF THIS LIBRARY,
// BUT WE WANT TO BE SURE THE STUDENTS SEE THIS CODE IN SOURCE/ SO THEY READ IT.

#include "MicroBit.h"
extern MicroBit uBit;

#define OLED_PIXEL_ON true
#define OLED_PIXEL_OFF false
#define OLED_WIDTH 128
#define OLED_HEIGHT 64

void SSD1306_init();
void SSD1306_setPixel(uint8_t x, uint8_t y, bool on);
void SSD1306_clearColumn(uint8_t col);

#endif // !__SD1306_OBF_H
